config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/2.0.0
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/indigo-dc/orchestrator-dashboard:
      branch: main
      repo: https://github.com/indigo-dc/orchestrator-dashboard
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/indigo-dc/orchestrator-dashboard git:
        commands:
        - /usr/bin/env sh .sqa/script.surly-tangerine-rat.sh
        container: qc.acc_lovely-brass-iguana
  QC.Doc:
    repos:
      github.com/indigo-dc/orchestrator-dashboard find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.beady-cardinal-hornet.sh
        container: qc.doc_skinny-amethyst-tarantula
      github.com/indigo-dc/orchestrator-dashboard git:
        commands:
        - /usr/bin/env sh .sqa/script.sloppy-pumpkin-capybara.sh
        container: qc.doc_skanky-denim-koala
  QC.Lic:
    repos:
      github.com/indigo-dc/orchestrator-dashboard licensee:
        commands:
        - /usr/bin/env sh .sqa/script.messy-saffron-forest.sh
        container: qc.lic_shaky-razzmatazz-kangaroo
  QC.Ver:
    repos:
      github.com/indigo-dc/orchestrator-dashboard get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.scummy-charcoal-peccary.sh
        container: qc.ver_beady-wisteria-bombay
timeout: 5400
